name: Check for update

on:
  push:
  # on demand
  workflow_dispatch:
  schedule:
    - cron: "8 * * * *"

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - name: check if new version is out
        run: |
          mv latest-version prev-version
          curl -s https://api.github.com/repos/paritytech/polkadot/releases/latest | jq -r .tag_name > latest-version
          cat prev-version latest-version
          # non-zero if there are differences
          diff prev-version latest-version
