name: Check for update

on:
  push:
  # on demand
  workflow_dispatch:
  schedule:
    - cron: "8 * * * *"

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: check if new version is out
        id: check
        continue-on-error: true
        run: |
          mv latest-version prev-version
          curl -s https://api.github.com/repos/paritytech/polkadot/releases/latest | jq -r .tag_name > latest-version
          cat prev-version latest-version
          # non-zero if there are differences
          diff prev-version latest-version
