name: Update overlay

on:
  workflow_run:
    workflows: [ "Check for update" ]
    types:
      - completed

jobs:
  update-overlay:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: cachix/cachix-action@v8
        with:
          name: asymmetric
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - if: steps.check.outcome == 'failure'
        run: nix flake update --recreate-lock-file
      - if: steps.check.outcome == 'failure'
        name: nix build to save hash
        run: |
          echo "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" > hash
          nix build  |& awk '/got: / {print $2}' > hash
      - if: steps.check.outcome == 'failure'
        name: build again
        run: nix build -L --no-link
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[automation] update"
