name: Update overlay

on:
  # manually
  workflow_dispatch:
  workflow_run:
    workflows: [ "Check for update" ]
    types:
      - completed

jobs:
  update-overlay:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: asymmetric
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: fetch latest version
        run: curl -s https://api.github.com/repos/paritytech/polkadot/releases/latest | jq -r .tag_name > latest-version
      - run: nix flake update --recreate-lock-file
      - name: nix build to save hash
        run: |
          echo "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" > hash
          nix build  |& awk '/got: / {print $2}' > hash
      - name: build again
        run: nix build -L --no-link
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[automation] update"
