name: Update overlay

on:
  # on demand
  workflow_dispatch:
  # every hour, at minute 8
  schedule:
    - cron: "8 * * * *"

jobs:
  update-overlay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: asymmetric
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: check if new version is out
        id: check
        continue-on-error: true
        run: |
          mv latest-version prev-version
          curl -s https://api.github.com/repos/paritytech/polkadot/releases/latest | jq -r .tag_name > latest-version
          diff prev-version latest-version
      - if: steps.check.outcome == 'failure'
        run: nix flake update --recreate-lock-file
      - if: steps.check.outcome == 'failure'
        run: ./update.sh
      - if: steps.check.outcome == 'failure'
        run: nix build -L
