name: Update overlay

on:
  # on demand
  workflow_dispatch:
  # every fifteen minutes
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update-overlay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake update --recreate-lock-file
      - run: ./update.sh
      - run: nix build -L
      - uses: cachix/cachix-action@v8
        with:
          name: asymmetric
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
